[tool.black]
line-length = 88
target-version = ['py38']
include = '.pyi?$'
exclude = '''
(
    \frontend-project
  | migrations
  | \.git
  | \.eggs
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | \venv             # pycharm
  | \_build
  | build
  | dist
)
'''
