name: JavaScript files

on:
  push:
    paths:
    - 'frontend-project/design_pro/**'
  pull_request:
    paths:
    - 'frontend-project/design_pro/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install
      run: npm install
      working-directory: ./frontend-project/design_pro/
    - name: Lint
      run: npm run lint
      working-directory: ./frontend-project/design_pro/
    - name: Build
      run: npm run build
      working-directory: ./frontend-project/design_pro/
